import { C } from "./theme";

// ══════════════════════════════════════════════════════════════
// Shared inline-style generator
// Returns a style object set based on dark/light mode.
// ══════════════════════════════════════════════════════════════
export const gs = (dark) => ({
  app: {
    fontFamily: "'Inter','Segoe UI',Helvetica,Arial,sans-serif",
    background: dark ? C.dark : C.cream,
    minHeight: "100vh",
    color: dark ? "#E8E5F9" : C.soil,
    transition: "background .3s,color .3s",
  },
  card: {
    background: dark ? C.darkCard : C.white,
    borderRadius: 6,
    padding: 20,
    boxShadow: dark ? "none" : "0 1px 2px rgba(15,23,42,0.06)",
    border: `1px solid ${dark ? C.darkBorder : "#DDD9F3"}`,
    marginBottom: 16,
  },
  input: {
    width: "100%",
    padding: "9px 12px",
    borderRadius: 4,
    border: `1px solid ${dark ? "#3D3470" : "#D6D2F0"}`,
    fontSize: 13.5,
    outline: "none",
    boxSizing: "border-box",
    background: dark ? "#160F2E" : C.white,
    color: dark ? "#E8E5F9" : C.soil,
  },
  btn: (bg, outline) => ({
    background: outline ? "transparent" : bg || C.leaf,
    color: outline ? bg || C.leaf : C.white,
    border: `1px solid ${bg || C.leaf}`,
    padding: "8px 16px",
    borderRadius: 4,
    cursor: "pointer",
    fontWeight: 600,
    fontSize: 12.5,
    letterSpacing: "0.1px",
    transition: "all .15s",
  }),
  badge: (color) => ({
    background: color + "14",
    color,
    padding: "2px 8px",
    borderRadius: 3,
    fontSize: 10.5,
    fontWeight: 700,
    display: "inline-block",
    letterSpacing: "0.2px",
    textTransform: "uppercase",
    border: `1px solid ${color}30`,
  }),
  th: {
    textAlign: "left",
    padding: "9px 14px",
    background: dark ? "#160F2E" : "#EFEDFA",
    color: C.muted,
    fontSize: 10.5,
    fontWeight: 700,
    borderBottom: `1px solid ${dark ? C.darkBorder : "#DDD9F3"}`,
    textTransform: "uppercase",
    letterSpacing: "0.4px",
  },
  td: {
    padding: "10px 14px",
    borderBottom: `1px solid ${dark ? C.darkBorder : "#ECEAFB"}`,
    fontSize: 13,
    verticalAlign: "middle",
  },
  label: {
    fontSize: 11.5,
    fontWeight: 600,
    display: "block",
    marginBottom: 5,
    color: dark ? "#A39DC9" : C.muted,
    textTransform: "uppercase",
    letterSpacing: "0.3px",
  },
  sideBtn: (a, ac) => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    padding: "10px 20px",
    background: a ? (dark ? "#2A2154" : "#EFE9FE") : "transparent",
    color: a ? ac || C.leaf : C.muted,
    border: "none",
    cursor: "pointer",
    fontWeight: a ? 700 : 500,
    fontSize: 13,
    textAlign: "left",
    borderLeft: a ? `2px solid ${ac || C.leaf}` : "2px solid transparent",
  }),
  statCard: (color) => ({
    background: dark ? C.darkCard : C.white,
    borderRadius: 6,
    padding: 18,
    boxShadow: dark ? "none" : "0 1px 2px rgba(15,23,42,0.06)",
    border: `1px solid ${dark ? C.darkBorder : "#DDD9F3"}`,
    borderTop: `2px solid ${color}`,
    textAlign: "center",
  }),
});
